// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Requerimientos.Data;

#nullable disable

namespace Requerimientos.Migrations
{
    [DbContext(typeof(RequerimientosContext))]
    [Migration("20260111215910_AddKardexClass")]
    partial class AddKardexClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Requerimientos.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Prefijo")
                        .IsUnique();

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clase", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Combustible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoXGalon")
                        .HasColumnType("money");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal?>("GalonesRecibidos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GlnsEntregado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GlnsXLitro")
                        .HasColumnType("decimal(10,6)");

                    b.Property<TimeOnly?>("HoraEntrega")
                        .HasColumnType("time");

                    b.Property<decimal?>("Litros")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("money");

                    b.Property<int>("QuienRecibeId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalGalones")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("QuienRecibeId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Combustible", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Comprador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CondicionPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Evidencia")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal?>("Ingreso")
                        .HasColumnType("money");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("money");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Kardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DocumentoIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoSalida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("PerteneceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("money");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("money");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Proviene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuienEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("QuienRecibeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerteneceId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("QuienEntregaId");

                    b.HasIndex("QuienRecibeId");

                    b.ToTable("Kardex", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoferId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraIngreso")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<decimal>("HorometroFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorometroFinal2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorometroInicio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorometroInicio2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorometroTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorometroTotal2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PerteneceId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("TotalM3Desm")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int?>("VueltasVolq")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoferId");

                    b.HasIndex("PerteneceId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Movimiento", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Pertenece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Pertenece", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaRequerimiento")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Condicion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NroRequerimiento")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PerteneceId")
                        .HasColumnType("int");

                    b.Property<string>("Proviene")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PerteneceId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RUC")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Requerimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Detalle")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<int?>("Real")
                        .HasColumnType("int");

                    b.Property<string>("Solicitante")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Requerimiento", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripción")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCIBBVA")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CCIBCP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CCIInterbank")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Clase")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DNI")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NroBBVA")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroBCP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroInterbank")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Trabajador", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Simbolo")
                        .IsUnique();

                    b.ToTable("Unidad", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculo", (string)null);
                });

            modelBuilder.Entity("Requerimientos.Models.Combustible", b =>
                {
                    b.HasOne("Requerimientos.Models.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .IsRequired()
                        .HasConstraintName("FK_Combustible_Clase");

                    b.HasOne("Requerimientos.Models.Trabajador", "QuienRecibe")
                        .WithMany()
                        .HasForeignKey("QuienRecibeId")
                        .IsRequired()
                        .HasConstraintName("FK_Combustible_QuienRecibe_Trabajador");

                    b.HasOne("Requerimientos.Models.Trabajador", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .IsRequired()
                        .HasConstraintName("FK_Combustible_Responsable_Trabajador");

                    b.Navigation("Clase");

                    b.Navigation("QuienRecibe");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Requerimientos.Models.Compra", b =>
                {
                    b.HasOne("Requerimientos.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK_Compra_Proveedor");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Requerimientos.Models.Kardex", b =>
                {
                    b.HasOne("Requerimientos.Models.Pertenece", "Pertenece")
                        .WithMany("Kardex")
                        .HasForeignKey("PerteneceId")
                        .IsRequired()
                        .HasConstraintName("FK_Kardex_Pertenece");

                    b.HasOne("Requerimientos.Models.Producto", "Producto")
                        .WithMany("Kardex")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_Kardex_Producto");

                    b.HasOne("Requerimientos.Models.Trabajador", "QuienEntrega")
                        .WithMany("KardexEntregados")
                        .HasForeignKey("QuienEntregaId")
                        .IsRequired()
                        .HasConstraintName("FK_Kardex_QuienEntrega_Trabajador");

                    b.HasOne("Requerimientos.Models.Trabajador", "QuienRecibe")
                        .WithMany("KardexRecibidos")
                        .HasForeignKey("QuienRecibeId")
                        .IsRequired()
                        .HasConstraintName("FK_Kardex_QuienRecibe_Trabajador");

                    b.Navigation("Pertenece");

                    b.Navigation("Producto");

                    b.Navigation("QuienEntrega");

                    b.Navigation("QuienRecibe");
                });

            modelBuilder.Entity("Requerimientos.Models.Movimiento", b =>
                {
                    b.HasOne("Requerimientos.Models.Trabajador", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Chofer_Trabajador");

                    b.HasOne("Requerimientos.Models.Pertenece", "Pertenece")
                        .WithMany("Movimientos")
                        .HasForeignKey("PerteneceId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Pertenece");

                    b.HasOne("Requerimientos.Models.Proveedor", "Proveedor")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Proveedor");

                    b.HasOne("Requerimientos.Models.Vehiculo", "Vehiculo")
                        .WithMany("Movimientos")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Vehiculo");

                    b.Navigation("Chofer");

                    b.Navigation("Pertenece");

                    b.Navigation("Proveedor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Requerimientos.Models.Producto", b =>
                {
                    b.HasOne("Requerimientos.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Categoria");

                    b.HasOne("Requerimientos.Models.Pertenece", "Pertenece")
                        .WithMany("Productos")
                        .HasForeignKey("PerteneceId")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Pertenece");

                    b.HasOne("Requerimientos.Models.Unidad", "Unidad")
                        .WithMany("Productos")
                        .HasForeignKey("UnidadId")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Unidad");

                    b.Navigation("Categoria");

                    b.Navigation("Pertenece");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Requerimientos.Models.Usuario", b =>
                {
                    b.HasOne("Requerimientos.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Requerimientos.Models.Vehiculo", b =>
                {
                    b.HasOne("Requerimientos.Models.Clase", "Clase")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClaseId")
                        .IsRequired()
                        .HasConstraintName("FK_Vehiculo_Clase");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("Requerimientos.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Requerimientos.Models.Clase", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Requerimientos.Models.Pertenece", b =>
                {
                    b.Navigation("Kardex");

                    b.Navigation("Movimientos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Requerimientos.Models.Producto", b =>
                {
                    b.Navigation("Kardex");
                });

            modelBuilder.Entity("Requerimientos.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Requerimientos.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Requerimientos.Models.Trabajador", b =>
                {
                    b.Navigation("KardexEntregados");

                    b.Navigation("KardexRecibidos");
                });

            modelBuilder.Entity("Requerimientos.Models.Unidad", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Requerimientos.Models.Vehiculo", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
